/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Michael' at '02/12/16 13:22' with Gradle 2.6
 *
 * @author Michael, @date 02/12/16 13:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
