/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Michael' at '24/11/16 16:16' with Gradle 2.6
 *
 * @author Michael, @date 24/11/16 16:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
